services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: uvicorn speedcloud:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend
volumes:
  caddy-data:
  caddy-config:
