name: Playwright Tests
on: [push, pull_request]
env:
  PIP_EXTRA_INDEX_URL: ${{vars.PIP_EXTRA_INDEX_URL}}
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["chromium", "firefox", "webkit"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            'requirements/requirements*.txt'
      - name: Install backend dependencies
        run: python3 -m pip install -r requirements.txt
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{matrix.project}}
      - name: Run Playwright tests
        run: npx playwright test --project=${{matrix.project}} --reporter github